# Generated by Django 3.2.12 on 2022-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='images',
            field=models.ImageField(upload_to='post_media'),
        ),
    ]
