# Generated by Django 3.2.12 on 2022-03-26 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_register_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='description',
        ),
        migrations.RemoveField(
            model_name='register',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='place',
        ),
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_images'),
            preserve_default=False,
        ),
    ]
